Vagrant.configure('2') do |config|
  config.vm.box = 'archlinux/archlinux'

  config.vm.provider 'virtualbox' do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = '1024'
  end

  config.vm.provision :ansible do |ansible|
    # Run from root
    ansible.become = true
    ansible.playbook = 'playbook.yml'
  end
end
