Vagrant.configure('2') do |config|
  config.vm.box = 'archlinux/archlinux'

  config.vm.provider 'virtualbox' do |vb|
    vb.gui = true
    # Customize the amount of memory on the VM:
    vb.memory = '1024'
  end

  config.vm.provision "shell", path: "install.sh"
end
